# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh-fomanticui',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fh-fomanticui',
                'lib_path': 'fh_fomanticui'},
  'syms': { 'fh_fomanticui.card': {},
            'fh_fomanticui.fomantic': { 'fh_fomanticui.fomantic.FButton': ('core.html#fbutton', 'fh_fomanticui/fomantic.py'),
                                        'fh_fomanticui.fomantic.FColumn': ('core.html#fcolumn', 'fh_fomanticui/fomantic.py'),
                                        'fh_fomanticui.fomantic.FContainer': ('core.html#fcontainer', 'fh_fomanticui/fomantic.py'),
                                        'fh_fomanticui.fomantic.FDropdown': ('core.html#fdropdown', 'fh_fomanticui/fomantic.py'),
                                        'fh_fomanticui.fomantic.FForm': ('core.html#fform', 'fh_fomanticui/fomantic.py'),
                                        'fh_fomanticui.fomantic.FGrid': ('core.html#fgrid', 'fh_fomanticui/fomantic.py'),
                                        'fh_fomanticui.fomantic.FInput': ('core.html#finput', 'fh_fomanticui/fomantic.py')}}}
