# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh-ui',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fh-ui',
                'lib_path': 'fh_ui'},
  'syms': { 'fh_ui.card': {},
            'fh_ui.fomantic': { 'fh_ui.fomantic.FButton': ('core.html#fbutton', 'fh_ui/fomantic.py'),
                                'fh_ui.fomantic.FColumn': ('core.html#fcolumn', 'fh_ui/fomantic.py'),
                                'fh_ui.fomantic.FContainer': ('core.html#fcontainer', 'fh_ui/fomantic.py'),
                                'fh_ui.fomantic.FDropdown': ('core.html#fdropdown', 'fh_ui/fomantic.py'),
                                'fh_ui.fomantic.FForm': ('core.html#fform', 'fh_ui/fomantic.py'),
                                'fh_ui.fomantic.FGrid': ('core.html#fgrid', 'fh_ui/fomantic.py'),
                                'fh_ui.fomantic.FInput': ('core.html#finput', 'fh_ui/fomantic.py')}}}
