# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Elements/00_button.ipynb.

# %% auto 0
__all__ = ['FButton', 'FAnimatedButton']

# %% ../nbs/Elements/00_button.ipynb 3
from dataclasses import dataclass, asdict
from fastcore.utils import *
from fastcore.xml import *
from fastcore.xtras import *
from fastcore.meta import use_kwargs, delegates
from fasthtml.components import *

# %% ../nbs/Elements/00_button.ipynb 5
@delegates(Button, keep=True)
def FButton(*c, cls="ui button", **kwargs) -> FT:
    "A standard Fomantic UI Button, extending the existing Button FastTag"
    return Button(*c, cls=cls, **kwargs)

# %% ../nbs/Elements/00_button.ipynb 13
@delegates(Button, keep=True)
def FAnimatedButton(visible, hidden, tabindex=0, cls="ui animated button", **kwargs) -> FT:
    "Animates to show hidden content"
    return Button(Div(visible, cls="visible content"), Div(hidden, cls="hidden content"), cls=cls, **kwargs)
