# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/elements/06_icon.ipynb.

# %% auto 0
__all__ = ['Icon']

# %% ../nbs/elements/06_icon.ipynb 3
from dataclasses import dataclass, asdict
from fastcore.utils import *
from fastcore.xml import *
from fastcore.xtras import *
from fastcore.meta import use_kwargs, delegates
from fasthtml.components import *

# %% ../nbs/elements/06_icon.ipynb 4
@delegates(I, keep=True)
def Icon(desc, **kwargs) -> FT:
    "A Fomantic UI Icon"
    return I(cls=f"{desc} icon", style="visibility: visible;", **kwargs)
