project:
  type: website

format:
  html:
    minimal: true
    theme: none
    css: https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      - 00_core.ipynb
      - section: Elements
        contents: elements/*.ipynb

metadata-files: [nbdev.yml]
