# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_fomantic.ipynb.

# %% auto 0
__all__ = ['fomanticcss', 'fomanticlink', 'FButton', 'FContainer', 'FGrid', 'FColumn', 'FForm', 'FInput', 'FDropdown']

# %% ../nbs/02_fomantic.ipynb 2
from dataclasses import dataclass, asdict
from fastcore.utils import *
from fastcore.xml import *
from fastcore.meta import use_kwargs, delegates
from fasthtml.components import *

# %% ../nbs/02_fomantic.ipynb 3
fomanticcss = "https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.css"
fomanticlink = (Link(rel="stylesheet", href=fomanticcss),)

# %% ../nbs/02_fomantic.ipynb 4
@delegates(Button, keep=True)
def FButton(*c, cls="ui button", **kwargs) -> XT:
    "A Fomantic UI Button, extending the existing Button component"
    return Button(*c, cls=cls, **kwargs)

# %% ../nbs/02_fomantic.ipynb 6
@delegates(Div, keep=True)
def FContainer(*c, cls="ui container", **kwargs) -> XT:
    "A Fomantic UI Container"
    return Div(*c, cls=cls, **kwargs)

# %% ../nbs/02_fomantic.ipynb 8
@delegates(Div, keep=True)
def FGrid(*c, cls="ui grid", **kwargs) -> XT:
    "A Fomantic UI Grid"
    return Div(*c, cls=cls, **kwargs)

# %% ../nbs/02_fomantic.ipynb 11
@delegates(Div, keep=True)
def FColumn(*c, cls="column", **kwargs) -> XT:
    "A Fomantic UI Grid Column"
    if "width" in kwargs:
        # Convert number to word
        kwargs["width"] = num2word(kwargs["width"])
        cls = f"{kwargs.pop('width')} wide column"
    return Div(*c, cls=cls, **kwargs)

# %% ../nbs/02_fomantic.ipynb 14
@delegates(Form, keep=True)
def FForm(*c, cls="ui form", **kwargs)->XT:
    "A Fomantic UI Form"
    return Form(*c, cls=cls, **kwargs)

# %% ../nbs/02_fomantic.ipynb 16
@delegates(Div, keep=True)
def FInput(*c, cls="ui input", **kwargs)->XT:
    "A Semantic UI Input"
    return xt_hx('div', Input(*c, **kwargs), cls=cls)

# %% ../nbs/02_fomantic.ipynb 18
@delegates(xt_hx, keep=True)
def FDropdown(placeholder, options, cls="ui dropdown", **kwargs)->XT:
    "A Semantic UI Dropdown"
    opts = [Option(text=o, value=o) for o in options]
    return xt_hx('select', *opts, cls=cls, placeholder=placeholder, **kwargs)
