name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Install setuptools
        run: pip install setuptools

      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: '3.11'
          pre: 1
